### ISSUE TITLE
Cypress tests does not start when generating compodoc before

### ISSUE THREAD

**Issue by jogelin** [twittwer/nx-tools#30]
Hello,

I am using storybook + compodoc and I would like to use your library.

All of your configurations are working fine until I would like to use it to generate doc + run storybook before starting cypress:

```


    "ui": {
        ...
        "storybook": {
          ...
        },
        "compodoc": {
          ...
        },
        "storybook-ci": {
          "builder": "@nrwl/workspace:run-commands",
          "options": {
            "commands": ["npx nx run ui:compodoc:json", "npx nx run ui:storybook:ci"]
          }
        },
    }
...
    "ui-e2e": {
        ...
        "e2e": {
          "builder": "@nrwl/cypress:cypress",
          "options": {
            "cypressConfig": "apps/ui-e2e/cypress.json",
            "tsConfig": "apps/ui-e2e/tsconfig.e2e.json",
            "devServerTarget": "ui:storybook",
            "watch": true
          },
          "configurations": {
            "ci": {
              "devServerTarget": "ui:storybook-ci", --> this is pointing to the run commands custom config
              "watch": false,
              "headless": true
            }
          }
        },
    }
```

* The doc is generated
* The storybook is started
* Cypress does not start, the terminal stays on storybook

I have the feeling this is more related to the `run-commands` approach, any idea?

**Comment by twittwer** [comment]
By default the run-commands are executed in parallel. This is no problem if you already have a compodoc json file and storybook runs in watch mode, because the later generated compodoc json file is taken into account by storybooks watch mode.
In case of CI it may be required to execute compodoc and storybook in sequence:
```json
        "storybook-ci": {
          "builder": "@nrwl/workspace:run-commands",
          "options": {
            "commands": ["npx nx run ui:compodoc:json", "npx nx run ui:storybook:ci"],
            "parallel": false <-- add this option
          }
        }
```

**Comment by jogelin** [comment]
Yes I tried that too but still locked on storybook execution.

I think the `devServerTarget ` isn't managing the execution in the same way as the @nrwl/workspace:run-commands

I found something https://github.com/nrwl/nx/issues/3748, not sure if it is related

**Comment by twittwer** [comment]
Sorry, for the long silence. Is it still an issue?
If it's still an issue is storybook's watch mode disabled in the `ui:storybook:ci` configuration?

**Comment by jogelin** [comment]
@twittwer 
in my config I have
```
        "storybook": {
          "builder": "@nrwl/storybook:storybook",
          "options": {
            "uiFramework": "@storybook/angular",
            "port": 4400,
            "config": {
              "configFolder": "libs/ui/.storybook"
            }
          },
          "configurations": {
            "ci": {
              "quiet": true,
              "watch": false
            }
          }
        },
```
still blocked on storybook, does not run tests

**Comment by jogelin** [comment]
Finally, I am using the dependsOn property directly.

But I think the issue was caused by the [readyWhen](https://github.com/nrwl/nx/issues/3748) that I had to specify
