### ISSUE TITLE
[Bug] Wrong Path Resolution in Nx Workspace

### ISSUE THREAD

**Issue by KingDarBoja** [twittwer/nx-tools#31]
Hello there!

I just decided to give a try to this plugin in some nx workspace with several angular apps and libraries but got the below error after following the steps at [workspace-docs](https://github.com/twittwer/nx-tools/tree/master/libs/compodoc#workspace-docs) in this [example repository](https://github.com/KingDarBoja/ngfire-showcase) of mine.

```console
Unhandled Rejection at: Promise {
  <rejected> Error: ENOENT: no such file or directory, open 'D:\Programming\angular_projects\ngfire-showcase\C:\Users\INTEL\AppData\Local\Temp\0T9sI2\web-core-configuration-firebase.md'
      at Object.openSync (fs.js:440:3)
      at Object.readFileSync (fs.js:342:35)
      at FileEngine.getSync (D:\Programming\angular_projects\ngfire-showcase\node_modules\@compodoc\compodoc\dist\application-54cd2170.js:1242:19)
      at MarkdownEngine.getTraditionalMarkdownSync (D:\Programming\angular_projects\ngfire-showcase\node_modules\@compodoc\compodoc\dist\application-54cd2170.js:4287:49)
```

After digging a bit into the source code, I noticed [this line](https://github.com/twittwer/nx-tools/blob/7120c5c4cbbd152a145cea31711098f09c18024c/libs/compodoc/src/builders/compodoc/compodoc-utils.ts#L39) that defines the `tmpFolder` where to write the markdown additional files. 

However seems like this is not correct when you try to run the builder to generate docs on Windows as it will try to resolve to some weird path (the tmpFolder + the filename to look for), so I decided to replace it by `const tmpFolder = fs.mkdtempSync('compodoc');` and the script didn't throw the error and got the expected output html files.

**Profit**

![image](https://user-images.githubusercontent.com/30560560/113783788-e94b9580-96f9-11eb-8748-dcf843a63c28.png)

I can submit a PR with the fix if that's okay and also implement the os strategy in GH Actions to avoid such issues when adding new features or bugfixes.

Cheers!

**Comment by twittwer** [comment]
Interesting 🤔  
I'm using it on Windows and didn't experience this problem so far - I'll try to reproduce...
