### ISSUE TITLE
Npm package @twittwer/compodoc not found

### ISSUE THREAD

**Issue by marek-ganko** [twittwer/nx-tools#41]
For some reason this package is unavailable on global npm registry: https://www.npmjs.com/package/@twittwer/compodoc

<img width="1090" alt="Screenshot 2021-07-06 at 16 03 07" src="https://user-images.githubusercontent.com/6524355/124613632-b8533c00-de73-11eb-965d-8e8274d45c78.png">

**Comment by mackelito** [comment]
Seems to work fine now..

**Comment by twittwer** [comment]
I will close it as it seems to be no problem anymore
