### ISSUE TITLE
Not able to `nx add @twittwer/compodoc`

### ISSUE THREAD

**Issue by mahnuh** [twittwer/nx-tools#43]
When trying to add @twittwer/compodoc to my workspace by running `nx add @twittwer/compodoc` I only get the following error: `Could not find project "@twittwer/compodoc"`. I'm using `@nrwl/workspace@12.5.6`.

**Comment by twittwer** [comment]
I tried the latest version and v12.5.6 but cannot reproduce the problem.  
If the problem still exists in your environment, just comment with some more details.
