### ISSUE TITLE
compdoc nx plugin: support nx per-project configuration

### ISSUE THREAD

**Issue by christianacca** [twittwer/nx-tools#46]
Seems like compdoc nx plugin does not work with a repo that uses [per-project configuration](https://blog.nrwl.io/per-project-configuration-storybook-support-for-angular-12-auto-refresh-for-dependency-graph-and-bcd2d1e06658#aeaf)

```bash
➜  static-web-apps-auth git:(master) npm run nx -- add @twittwer/compodoc                      

> swa-auth@0.0.0 nx /Users/christian.crowhurst/Documents/git/static-web-apps-auth
> nx "add" "@twittwer/compodoc"

Unable to read workspace file '/Users/christian.crowhurst/Documents/git/static-web-apps-auth/angular.json': Invalid format version detected - Expected:[ 1 ] Found: [ 2 ]
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! swa-auth@0.0.0 nx: `nx "add" "@twittwer/compodoc"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the swa-auth@0.0.0 nx script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/christian.crowhurst/.npm/_logs/2021-08-19T08_44_46_644Z-debug.log

```

Tried installing the dev deps manually and then run the schematic, but that doesn't add the necessary script entries to the project.json

**Comment by twittwer** [comment]
Yes, it is currently not supported - might require some refactorings to handle this setup.

**Comment by the-ult** [comment]
Would be great if this plugin would support the per-project configuration, since it is gonna be the default wilt NX 13. (probably november)

**Comment by twittwer** [comment]
I'm working on a rewrite base on the nrwl's devkit to ensure compatibility with all the workspace setups.
ATM it should work with angular.json & workspace.json but not with per-project-configuration.

**Comment by twittwer** [comment]
I'm sorry for the long response time 🙈
But now the latest version (>=1.6.0) supports standalone project configurations 🎉

**Comment by christianacca** [comment]
Thanks :-)
