### ISSUE TITLE
Use Compodoc watch json mode

### ISSUE THREAD

**Issue by manuelmeister** [twittwer/nx-tools#47]
https://github.com/twittwer/nx-tools/blob/1c521455fc0eaa64c5230277333b8b9a37ed9681/libs/compodoc/src/builders/compodoc/compodoc-utils.ts#L288-L298
Is this still necessary, now that compodoc supports watch mode with json: compodoc/compodoc#1087?

**Comment by twittwer** [comment]
@manuelmeister Have you tried compodoc's watch mode for json format?  
In my setup I had issues that it ignored some file changes.

**Comment by twittwer** [comment]
Since version 1.6.0 compodoc's internal watch mechanism is used for individual projects. The issues I described are related to the workspaceDocs mode (see #44), that's why the nodemon wrapper is currently still necessary for the watch mode in workspaceDocs.
