### ISSUE TITLE
No longer adds `'compodoc'` target to `cacheableOperations`

### ISSUE THREAD

**Issue by christianacca** [twittwer/nx-tools#54]
Before change to support nx workspace v2, 'compodoc' was added to the `cacheableOperations` element in nx.json.

That's no longer the case. Is this a regression or intentional?

**Comment by twittwer** [comment]
Thx for the issue, that was not intentional.
With v1.6.5 it will be added again, like before.

**Comment by christianacca** [comment]
Thanks!
