### ISSUE TITLE
Do not use package manager bin to execute compodoc

### ISSUE THREAD

**Issue by jogelin** [twittwer/nx-tools#56]
Usually in Nx repo, we create scripts in `package.json` to execute targets like:
```
...
    "start": "nx serve",
    "build": "nx build",
    "test": "nx test",
    "e2e": "nx e2e",
    "compodoc": "nx compodoc", <-- here the issue
...
```

But if you specify the script `compodoc`, and then generate your doc using `yarn compodoc my-app`, the executor will re-execute `yarn compodoc` behind and it will result to:

![image](https://user-images.githubusercontent.com/954509/146190006-d614e438-3ae2-4ff0-beb1-3e9d5f284c80.png)

@twittwer Would it be possible to not use `getPackageManagerCommand()` but directly the binary in the `node_modules`?

**Comment by twittwer** [comment]
Thx for the issue, as I use npm the issue doesn't occur 🙈 
Version `1.6.6` executes compodoc directly from the `node_modules`
