### ISSUE TITLE
Add some doc for developer participation (have issues)

### ISSUE THREAD

**Issue by jogelin** [twittwer/nx-tools#60]
Hey,

I would to see if I can make some propositions of PRs but I cannot bootstrap the library:

the `package-lock` in targeting localhost:
![image](https://user-images.githubusercontent.com/954509/152346135-dd99c9be-c23d-4625-b69d-4247dc636e7a.png)

if I remove it, some library doesn't exist:
![image](https://user-images.githubusercontent.com/954509/152346232-ebf85630-42b7-4f91-a1d1-7c7e8bfe931e.png)

This is only for the root of the repository. Seems ok for compodoc only by using yarn...

**Comment by twittwer** [comment]
Sorry for your issues.
I accidentally committed my test with the local registry 🙈 
I added a short guide about the local registry in the [README.md](https://github.com/twittwer/nx-tools#how-to-try-changes-locally).
Does this address your problems?
