### ISSUE TITLE
Workspace docs & unit test coverage

### ISSUE THREAD

**Issue by maxbebaasuro** [twittwer/nx-tools#67]
HI!, 

could you provide some example on how to setup unit test coverage in combination with workspace docs?

Thanks!

**Comment by twittwer** [comment]
I haven't anything with unit test coverage in compodoc yet, what do you want to do?

**Comment by mbeckenbach** [comment]
Compodoc can include test coverage reports. I’ll send an example later next week.

**Comment by twittwer** [comment]
@mbeckenbach Is there still an issue?

**Comment by maxbebaasuro** [comment]
@twittwer Hey, sorry that i didnt reply anymore. Had no time to investigate that further. Deadlines. :-D 
If it's still relevant i'll reopen the issue when we go on with that topic.
