### ISSUE TITLE
Cannot find module 'nx/src/generators/utils/json'

### ISSUE THREAD

**Issue by chrisj-skinner** [twittwer/nx-tools#70]
Hi,

Have an NX project 13.10.2 with an angular app running storybook

Followed the setup at: https://www.npmjs.com/package/@twittwer/compodoc#generator

Seeing the following error `Cannot find module 'nx/src/generators/utils/json'` after running `npx nx g @twittwer/compodoc:config`

See screenshot

<img width="1578" alt="Screenshot 2022-08-31 at 21 47 17" src="https://user-images.githubusercontent.com/5794048/187780248-028140d4-e5dc-46bd-8360-f6acdbac2609.png">

The same error appears no matter what I enter as a project name.

Any help, much appreciated.

**Comment by twittwer** [comment]
I already had a look at it - The problem is the older nx version.
I will look into it & asked for some info in the nx slack on how to reference the nrwl/devkit without such issue.

**Comment by twittwer** [comment]
@chrisj-skinner with version 1.8.1 it should work, tested it against nx@latest & nx@13.10.2
